<a href="https://colab.research.google.com/github/the1975/Data-Processing/blob/main/Learning_Data_Processing/IMDb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import library yang dibutuhkan
import numpy as np
import pandas as pd
import kagglehub
import os

# Download dataset latest version
path = kagglehub.dataset_download("harshitseth809014/imdb-top-10000-movies")

print(os.listdir(path))
print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/harshitseth809014/imdb-top-10000-movies/1.archive...

100%|██████████| 1.39M/1.39M [00:00<00:00, 86.4MB/s]

Extracting files...
['movies.csv']
Path to dataset files: /root/.cache/kagglehub/datasets/harshitseth809014/imdb-top-10000-movies/versions/1

In [ ]:
# Menampilkan dataset
df = pd.read_csv(path +'/movies.csv' )
df.head()

,Unnamed: 0,id,title,release_date,overview,popularity,vote_average,vote_count
0,0,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",120.809,8.7,17290
1,1,278,The Shawshank Redemption,1994-09-23,Framed in the 1940s for the double murder of h...,92.415,8.7,23086
2,2,315162,Puss in Boots: The Last Wish,2022-12-07,Puss in Boots discovers that his passion for a...,12066.070,8.6,1677
3,3,240,The Godfather Part II,1974-12-20,In the continuing saga of the Corleone crime f...,73.078,8.6,10466
4,4,424,Schindler's List,1993-12-15,The true story of how businessman Oskar Schind...,60.267,8.6,13659

In [ ]:
df.columns

Index(['Unnamed: 0', 'id', 'title', 'release_date', 'overview', 'popularity',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
# Melihat tipe data
df.dtypes

Unnamed: 0        int64
id                int64
title            object
release_date     object
overview         object
popularity      float64
vote_average    float64
vote_count        int64
dtype: object

In [ ]:
df.shape

(10000, 8)

In [ ]:
df.isnull().sum().sort_values(ascending=False)

overview        2
Unnamed: 0      0
title           0
id              0
release_date    0
popularity      0
vote_average    0
vote_count      0
dtype: int64

In [ ]:
# cek data duplikat
print(f'Banyaknya data duplikat sebanyak: {df.duplicated().sum()}')

Banyaknya data duplikat sebanyak: 0

In [ ]:
# liat hasil
print(f'Banyaknya data duplikat sebanyak: {df.duplicated().sum()}')

Banyaknya data duplikat sebanyak: 0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    10000 non-null  int64
 1   id            10000 non-null  int64
 2   title         10000 non-null  object
 3   release_date  10000 non-null  object
 4   overview      9998 non-null   object
 5   popularity    10000 non-null  float64
 6   vote_average  10000 non-null  float64
 7   vote_count    10000 non-null  int64
dtypes: float64(2), int64(3), object(3)
memory usage: 625.1+ KB

**Data Cleaning**

In [ ]:
# Handle mising value pada kolom overview
df['overview'] = df['overview'].fillna('No overview Available')

# Menganti tipe data pada kolom release_date
df['release_date'] = pd.to_datetime(df['release_date'])

df['year'] = df['release_date'].dt.year
df['month'] = df['release_date'].dt.month
df['day'] = df['release_date'].dt.day

# Mengapus kolom unnamed: 0
df.drop(columns=['Unnamed: 0'], inplace=True)

# Menghapus data duplikat
df.drop_duplicates(inplace=True)

In [ ]:
# cek hasilnya
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 9994 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            9994 non-null   int64
 1   title         9994 non-null   object
 2   release_date  9994 non-null   datetime64[ns]
 3   overview      9994 non-null   object
 4   popularity    9994 non-null   float64
 5   vote_average  9994 non-null   float64
 6   vote_count    9994 non-null   int64
 7   year          9994 non-null   int32
 8   month         9994 non-null   int32
 9   day           9994 non-null   int32
dtypes: datetime64[ns](1), float64(2), int32(3), int64(2), object(2)
memory usage: 741.7+ KB

,id,title,release_date,overview,popularity,vote_average,vote_count,year,month,day
0,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",120.809,8.7,17290,1972,3,14
1,278,The Shawshank Redemption,1994-09-23,Framed in the 1940s for the double murder of h...,92.415,8.7,23086,1994,9,23
2,315162,Puss in Boots: The Last Wish,2022-12-07,Puss in Boots discovers that his passion for a...,12066.070,8.6,1677,2022,12,7
3,240,The Godfather Part II,1974-12-20,In the continuing saga of the Corleone crime f...,73.078,8.6,10466,1974,12,20
4,424,Schindler's List,1993-12-15,The true story of how businessman Oskar Schind...,60.267,8.6,13659,1993,12,15

In [ ]:
df['vote_average'].describe()

count    9994.00000
mean        6.70032
std         0.69040
min         5.40000
25%         6.20000
50%         6.70000
75%         7.20000
max         8.70000
Name: vote_average, dtype: float64

In [ ]:
df['popularity'].describe()

count     9994.000000
mean        31.160775
std        151.025563
min          0.600000
25%         11.653250
50%         16.620000
75%         27.403000
max      12066.070000
Name: popularity, dtype: float64

In [ ]:
df['vote_count'].describe()

count     9994.000000
mean      1609.551831
std       2756.766706
min        200.000000
25%        320.000000
50%        602.000000
75%       1526.000000
max      32977.000000
Name: vote_count, dtype: float64

In [ ]:
q25 = df['popularity'].quantile(0.25)
q75 = df['popularity'].quantile(0.75)

df['popularity_category'] = pd.cut(df['popularity'], bins = [0, q25, q75, float('inf')], labels = ['Kurang populer', 'Sedang', 'Populer'])

In [ ]:
df.head(20)

,id,title,release_date,overview,popularity,vote_average,vote_count,year,month,day,popularity_category
0,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",120.809,8.7,17290,1972,3,14,Populer
1,278,The Shawshank Redemption,1994-09-23,Framed in the 1940s for the double murder of h...,92.415,8.7,23086,1994,9,23,Populer
2,315162,Puss in Boots: The Last Wish,2022-12-07,Puss in Boots discovers that his passion for a...,12066.070,8.6,1677,2022,12,7,Populer
3,240,The Godfather Part II,1974-12-20,In the continuing saga of the Corleone crime f...,73.078,8.6,10466,1974,12,20,Populer
4,424,Schindler's List,1993-12-15,The true story of how businessman Oskar Schind...,60.267,8.6,13659,1993,12,15,Populer
5,19404,Dilwale Dulhania Le Jayenge,1995-10-19,"Raj is a rich, carefree, happy-go-lucky second...",29.629,8.6,4024,1995,10,19,Populer
6,129,Spirited Away,2001-07-20,"A young girl, Chihiro, becomes trapped in a st...",83.674,8.5,13815,2001,7,20,Populer
7,389,12 Angry Men,1957-04-10,The defense and the prosecution have rested an...,35.011,8.5,6958,1957,4,10,Populer
8,372058,Your Name.,2016-08-26,High schoolers Mitsuha and Taki are complete s...,108.319,8.5,9408,2016,8,26,Populer
9,496243,Parasite,2019-05-30,"All unemployed, Ki-taek's family takes peculia...",85.274,8.5,15067,2019,5,30,Populer
10,372754,Dou kyu sei – Classmates,2016-02-20,"Rihito Sajo, an honor student with a perfect s...",13.019,8.5,285,2016,2,20,Sedang
11,497,The Green Mile,1999-12-10,A supernatural tale set on death row in a Sout...,107.934,8.5,14868,1999,12,10,Populer
12,155,The Dark Knight,2008-07-14,Batman raises the stakes in his war on crime. ...,93.249,8.5,28978,2008,7,14,Populer
13,680,Pulp Fiction,1994-09-10,"A burger-loving hit man, his philosophical par...",72.833,8.5,24445,1994,9,10,Populer
14,429,"The Good, the Bad and the Ugly",1966-12-23,While the Civil War rages on between the Union...,59.322,8.5,7125,1966,12,23,Populer
15,13,Forrest Gump,1994-06-23,A man with a low IQ has accomplished great thi...,86.447,8.5,23958,1994,6,23,Populer
16,696374,Gabriel's Inferno,2020-05-29,An intriguing and sinful exploration of seduct...,14.884,8.5,2319,2020,5,29,Sedang
17,122,The Lord of the Rings: The Return of the King,2003-12-01,Aragorn is revealed as the heir to the ancient...,90.204,8.5,20931,2003,12,1,Populer
18,769,GoodFellas,1990-09-12,"The true story of Henry Hill, a half-Irish, ha...",45.325,8.5,10876,1990,9,12,Populer
19,724089,Gabriel's Inferno: Part II,2020-07-31,Professor Gabriel Emerson finally learns the t...,15.571,8.5,1456,2020,7,31,Sedang

In [ ]:
low = df[df['popularity_category'] == 'Kurang populer']
low.head(10)

,id,title,release_date,overview,popularity,vote_average,vote_count,year,month,day,popularity_category
24,12477,Grave of the Fireflies,1988-04-16,"In the final months of World War II, 14-year-o...",0.600,8.4,4460,1988,4,16,Kurang populer
36,92321,Hotarubi no Mori e,2011-09-17,One hot summer day a little girl gets lost in ...,0.600,8.4,898,2011,9,17,Kurang populer
46,40096,A Dog's Will,2000-09-15,The lively João Grilo and the sly Chicó are po...,10.042,8.4,951,2000,9,15,Kurang populer
63,12493,High and Low,1963-03-01,An executive of a shoe company becomes a victi...,10.195,8.3,657,1963,3,1,Kurang populer
71,644479,Dedicated to my ex,2019-11-01,"The film tells the story of Ariel, a 21-year-o...",8.598,8.3,478,2019,11,1,Kurang populer
106,42269,We All Loved Each Other So Much,1974-12-21,Three partisans bound by a strong friendship r...,9.945,8.3,448,1974,12,21,Kurang populer
108,31414,Satantango,1994-02-08,Inhabitants of a small village in Hungary deal...,10.968,8.2,211,1994,2,8,Kurang populer
134,313106,Doctor Who: The Day of the Doctor,2013-11-23,"In 2013, something terrible is awakening in Lo...",10.124,8.2,667,2013,11,23,Kurang populer
148,2457,Children of Paradise,1945-03-15,"Nathalie falls for Baptiste Debureau, a mime. ...",10.855,8.2,322,1945,3,15,Kurang populer
149,26451,Investigation of a Citizen Above Suspicion,1970-10-16,"Rome, Italy. After committing a heinous crime,...",11.365,8.2,639,1970,10,16,Kurang populer

In [ ]:
medium = df[df['popularity_category'] == 'Sedang']
medium.head(10)

,id,title,release_date,overview,popularity,vote_average,vote_count,year,month,day,popularity_category
10,372754,Dou kyu sei – Classmates,2016-02-20,"Rihito Sajo, an honor student with a perfect s...",13.019,8.5,285,2016,2,20,Sedang
16,696374,Gabriel's Inferno,2020-05-29,An intriguing and sinful exploration of seduct...,14.884,8.5,2319,2020,5,29,Sedang
19,724089,Gabriel's Inferno: Part II,2020-07-31,Professor Gabriel Emerson finally learns the t...,15.571,8.5,1456,2020,7,31,Sedang
22,346,Seven Samurai,1954-04-26,A samurai answers a village's request for prot...,23.720,8.4,2912,1954,4,26,Sedang
23,704264,Primal: Tales of Savagery,2019-11-21,Genndy Tartakovsky's Primal: Tales of Savagery...,21.272,8.4,252,2019,11,21,Sedang
28,761053,Gabriel's Inferno: Part III,2020-11-19,The final part of the film adaption of the ero...,20.143,8.4,1008,2020,11,19,Sedang
34,667257,Impossible Things,2021-06-17,"Matilde is a woman who, after the death of her...",16.738,8.4,326,2021,6,17,Sedang
43,620249,The Legend of Hei,2019-08-27,"In the bustling human world, spirits live peac...",14.225,8.4,243,2019,8,27,Sedang
49,599,Sunset Boulevard,1950-08-10,A hack screenwriter writes a screenplay for a ...,19.031,8.4,2127,1950,8,10,Sedang
52,553512,Burn the Stage: The Movie,2018-11-15,A documentary following the worldwide famous m...,17.824,8.4,390,2018,11,15,Sedang

In [ ]:
high = df[df['popularity_category'] == 'Populer']
high.head(10)

,id,title,release_date,overview,popularity,vote_average,vote_count,year,month,day,popularity_category
0,238,The Godfather,1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",120.809,8.7,17290,1972,3,14,Populer
1,278,The Shawshank Redemption,1994-09-23,Framed in the 1940s for the double murder of h...,92.415,8.7,23086,1994,9,23,Populer
2,315162,Puss in Boots: The Last Wish,2022-12-07,Puss in Boots discovers that his passion for a...,12066.070,8.6,1677,2022,12,7,Populer
3,240,The Godfather Part II,1974-12-20,In the continuing saga of the Corleone crime f...,73.078,8.6,10466,1974,12,20,Populer
4,424,Schindler's List,1993-12-15,The true story of how businessman Oskar Schind...,60.267,8.6,13659,1993,12,15,Populer
5,19404,Dilwale Dulhania Le Jayenge,1995-10-19,"Raj is a rich, carefree, happy-go-lucky second...",29.629,8.6,4024,1995,10,19,Populer
6,129,Spirited Away,2001-07-20,"A young girl, Chihiro, becomes trapped in a st...",83.674,8.5,13815,2001,7,20,Populer
7,389,12 Angry Men,1957-04-10,The defense and the prosecution have rested an...,35.011,8.5,6958,1957,4,10,Populer
8,372058,Your Name.,2016-08-26,High schoolers Mitsuha and Taki are complete s...,108.319,8.5,9408,2016,8,26,Populer
9,496243,Parasite,2019-05-30,"All unemployed, Ki-taek's family takes peculia...",85.274,8.5,15067,2019,5,30,Populer